Keymakh
Team-Violet-GB/GBmoney pull request #24
Opened 2020-07-08 19:46 UTC by Keymakh

Добавила значение по умолчанию

2020-07-08 19:55 UTC, andreybogan commented
![](https://github.trello.services/images/mini-trello-icon.png) [Создать миграции согласно схеме](https://trello.com/c/FpTvNF69/22-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D1%82%D1%8C-%D0%BC%D0%B8%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%81%D0%BE%D0%B3%D0%BB%D0%B0%D1%81%D0%BD%D0%BE-%D1%81%D1%85%D0%B5%D0%BC%D0%B5)

2020-07-09 11:38 UTC, andreybogan requested changes

2020-07-09 11:38 UTC, andreybogan commented on database/migrations/2020_07_06_192311_create_incomes_table.php
> +        Schema::create('incomes', function (Blueprint $table){
При добавлении внешних ключей ты используешь метод create, но так как таблицы уже созданы, то для манипуляций с таблицами (в том числе и для добавления внешних ключей) нужно использовать метод table. Должно получиться так: Schema::table('incomes', function (Blueprint $table).

2020-07-09 11:38 UTC, andreybogan commented on database/migrations/2020_07_06_192311_create_incomes_table.php
> +        Schema::create('incomes', function (Blueprint $table){
И так нужно поправить во всех миграциях.

2020-07-09 11:38 UTC, andreybogan commented on database/migrations/2020_07_06_193603_create_wallets_table.php
> +        });
Лена, при удалении внешнего ключа в массиве нужно указывать название только одной ячейки:
Schema::table('wallets', function (Blueprint $table){
            $table->dropForeign(['user_id']);
            $table->dropForeign(['icon_id']);
});
В противном случае формируется неправильное имя и при удалении возникает ошибка. Поправь это, пожалуйста, во всех миграциях, где такое встречается.

2020-07-09 11:38 UTC, andreybogan commented on database/migrations/2020_07_06_195006_create_transaction_table.php
> +        Schema::create('transaction', function (Blueprint $table) {
В этой миграции везде указано неправильное название таблицы (transaction), правильное название transactions

2020-07-10 05:09 UTC, andreybogan requested changes
И нужно выпилить из git файл public/js/app.js, я вроде бы писал тебе об этом. Если комментарий где-то потерялся, то как это сделать написано в документе https://docs.google.com/document/d/1zq3jTjO_mU6qQwnSY9JUkijYAuOVvmk1IuqzeScwLG0/edit в самом низу.

2020-07-10 05:09 UTC, andreybogan commented on database/migrations/2014_10_12_000000_create_users_table.php
> -            $table->string('password');
Лена, я бы не стал трогать миграции, которые ларавел поставляет по умолчанию, если, конечно, мы не добавляем дополнительный функционал. Если unsigned и максимальная длина для string это нормально, то вот добавление точности 6 в строчку  $table->timestamp('email_verified_at', 6)->nullable(); совсем не правильно, так как этот параметр поддерживается только в laravel 7, а у нас версия 5.8 Так что этот параметр нужно убрать.

2020-07-10 05:09 UTC, andreybogan commented on database/migrations/2020_07_06_172728_create_icons_table.php
> +            $table->bigIncrements('id')->unsigned();
Здесь был указана правильный параметр increments, так как иконок не больше сотни, и нам не нужны сверх большие числовые индексы на это поле. Вернуть.

2020-07-10 05:09 UTC, andreybogan commented on database/migrations/2020_07_06_193603_create_wallets_table.php
> +        });
Эта ошибка так и не исправлена, см. комментарий выше.

2020-07-10 05:18 UTC, andreybogan commented on database/migrations/2020_07_06_172728_create_icons_table.php
> +            $table->bigIncrements('id')->unsigned();
Да, и хорошо, что это произошло, потому что я сразу и не заметил что в связанных по внешнему ключу таблицах (wallets, expenses, incomes) на поле icon_id стоит bigInteger('icon_id'), а нужен increments('icon_id'), как и в таблице icons. Тоже поправь пожалуйста.

2020-07-10 09:54 UTC, Efrony submitted a review, later dismissed

2020-07-10 11:30 UTC, andreybogan approved these changes

2020-07-10 11:37 UTC, Efrony approved these changes

2020-07-10 11:39 UTC, merged