Api registration
Team-Violet-GB/GBmoney pull request #27
Opened 2020-07-10 10:33 UTC by Tuinov

Подгрузил laravel passport и сделал апи регистрации. Документация и скриншот отработки запроса из  postman в трелло.

2020-07-10 11:01 UTC, Tuinov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Установка и настройка Laravel Passport](https://trello.com/c/yFzH2iig/55-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-laravel-passport)

2020-07-10 11:02 UTC, Tuinov commented
![](https://github.trello.services/images/mini-trello-icon.png) [Реализовать регистрацию пользователя](https://trello.com/c/xXOcivOJ/45-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D1%8E-%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F)

2020-07-10 12:50 UTC, Efrony submitted a review, later dismissed

2020-07-10 17:27 UTC, Efrony approved these changes

2020-07-10 18:44 UTC, andreybogan requested changes

2020-07-10 18:44 UTC, andreybogan commented on app/Http/Controllers/AuthController.php
> +            'password' => ['required', 'min:6'],
Женя, для поля password нужно сделать вот такие проверки 'password' => ['required', 'string', 'min:6', 'confirmed']

2020-07-11 08:06 UTC, Efrony approved these changes

2020-07-11 08:17 UTC, andreybogan approved these changes

2020-07-11 08:17 UTC, merged